version: '3'
services:
  event-service:
    image: takeaway/bob-challenge-event-service:1.0.0
    container_name: event-service
    ports:
      - 8090:8090
    environment:
      - 'JAVA_OPTS= -Dlogging.config=classpath:logback-local.xml -Dspring.profiles.active=local'
    networks:
      - local_default

networks:
  local_default:
    external: true